spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: Chj7o1mXGCn0bbPsQcDu
  jpa:
    show-sql: true
websiteUrl: http://localhost:4242