#spring:
#  datasource:
#    url: ${SPRING_DATASOURCE_URL}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#websiteUrl: https//api.mystore.com
spring:
  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&serverTimezone=UTC
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

websiteUrl: https://api.mystore.com